name: Image CI
on:
  push:
    branches:
      - c10s
    pull_requests:

permissions: write-all

jobs:
  image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Release string
        run: echo "release=$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"
        id: release
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          sudo podman pull centos:stream10-development
      - name: Get source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version source
        run: |
          VER=${{ steps.release.outputs.release }}
          sed -i "s/-Image/-$VER/g" config.xml
      - name: Create container and build image
        run: |
          sudo mkdir images
          sudo podman build --tag imagebuilder -f Containerfile
          CID="$(sudo podman run --privileged --rmi -v /dev:/dev:dev,z -v $PWD:/sources:rw,z,shared,bind,U --workdir=/sources -d imagebuilder)"
          sudo podman exec $CID kiwi-ng --type=oem --profile="GCE" --color-output system build --description ./ --target-dir ./images
          sudo podman stop $CID
#      - name: Sign
#        uses: FKLC/sign-files-action@v1.0.0
#        with:
#          privateKey: ${{ secrets.PRIVATE_KEY }}
#          extension: '.sha256.sig'
#          outputFolder: 'images'
#          files: |
#            images/*.raw
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "images/*.raw"
          tag: ${{ steps.release.outputs.release }}
          commit: c10s
#          artifacts: "public_key.pem,images/*.raw,images/*.sha256.sig"
#          name: ${{ steps.release.outputs.release }}
#          tag: ${{ steps.release.outputs.release }}
