name: Image CI
on:
  push:
    branches:
      - c10s-rpi
    pull_requests:

permissions: write-all

jobs:
  image:
    name: Build Image
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Release string
        run: echo "release=$(date +%Y%m%d%H%M)" >> "$GITHUB_OUTPUT"
        id: release
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman xz-utils
          sudo podman pull centos:latest
      - name: Get source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Version source
        run: |
          VER=${{ steps.release.outputs.release }}
          sed -i "s/-Image/-rpi64-$VER/g" config.xml
      - name: Create container and build images
        run: |
          export RUID=$(id -u)
          export RGID=$(id -g)
          sudo mkdir images
          sudo mkdir iso
          sudo mkdir diskpi4
          sudo mkdir diskpi5
          sudo podman build --tag imagebuilder -f Containerfile
          CID="$(sudo podman run --privileged --rmi -v /dev:/dev:dev,z -v $PWD:/sources:rw,z,shared,bind,U --workdir=/sources -d imagebuilder)"
          sudo podman exec $CID kiwi-ng --type=iso --profile="LiveInstallPi" --color-output system build --description ./ --target-dir ./iso
          sudo sed -i "s/-rpi64/-pi4/g" config.xml
          sudo podman exec $CID kiwi-ng --type=oem --profile="MinimalDiskPi4" --color-output system build --description ./ --target-dir ./diskpi4
          sudo sed -i "s/-pi4/-pi5/g" config.xml
          sudo podman exec $CID kiwi-ng --type=oem --profile="MinimalDiskPi5" --color-output system build --description ./ --target-dir ./diskpi5
          sudo cp -rf iso/*.iso images/
          sudo cp -rf diskpi4/*.raw images/
          sudo cp -rf diskpi5/*.raw images/
          sudo podman stop $CID
          sudo chown -R $RUID:$RGID *
      - name: Compress raw disk image
        run: |
          IMGS=(images/*.raw)
          ISOS=(images/*.iso)
          xz -z -v -8 ${IMGS[0]}
          xz -z -v -8 ${IMGS[1]}
          xz -z -v -8 ${ISOS[0]}
      - name: Sign
        uses: FKLC/sign-files-action@v1.0.0
        with:
          privateKey: ${{ secrets.PRIVATE_KEY }}
          extension: '.sha256.sig'
          outputFolder: 'images'
          files: |
            images/*.iso.xz
            images/*.raw.xz
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "public_key.pem,images/*.iso.xz,images/*.raw.xz,images/*.sha256.sig"
          tag: ${{ steps.release.outputs.release }}
          commit: c10s-rpi
